spring:
  datasource:
    url: jdbc:mysql://localhost:3307/filedb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true

logging.level:
  com.example.springfiledbconsistency: debug
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.hibernate:
        type:
          descriptor:
            sql:
              BasicBinder=TRACE: